В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

def sigmoid(z):
    exp_arr = np.exp(-z)
    result = 1 / (1 + exp_arr)
    return result

z = np.array([-2, -1, 0, 1, 2])
sigmoid(z)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [2]:
def hypothesis(theta, X):
    z = np.dot(theta, X)
    result = sigmoid(z)
    return result

theta = np.array([0.5, -0.5])
X = np.array([[1, 1, 1, 1], [2, -1, 0, 1]])

hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [3]:
def compute_gradient(theta, X, y):
    h = hypothesis(theta, X)
    m = len(y)
    errors = h - y
    result = np.dot(X, errors) / m
    return result
    
y = np.array([1, 0, 1, 0])

compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [4]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.zeros(X.shape[0])
    
    theta_logs = []
    loss_logs = []
    
    for epoch in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta -= lr * gradient
        theta_logs.append(theta)
        
        loss = -np.mean(y * np.log(hypothesis(theta, X)) + (1 - y) * np.log(1 - hypothesis(theta, X)))
        loss_logs.append(loss)
    
        if epoch % 10 == 0:
            print(f"Epoch {epoch}: Loss = {loss}")

    return theta, theta_logs, loss_logs

In [5]:
lr = 0.1
epochs = 100

theta, theta_history, loss_history = full_batch_gradient_descent(X, y, lr, epochs)
print(f"Optimal theta: {theta}")

Epoch 0: Loss = 0.6870143589060703
Epoch 10: Loss = 0.6451908445881182
Epoch 20: Loss = 0.6237761864289744
Epoch 30: Loss = 0.6116448665334846
Epoch 40: Loss = 0.6041775933637039
Epoch 50: Loss = 0.5992897732553304
Epoch 60: Loss = 0.595947142599204
Epoch 70: Loss = 0.5935896469197548
Epoch 80: Loss = 0.5918903716027465
Epoch 90: Loss = 0.5906463568576532
Optimal theta: [-0.2893693   0.77655125]


#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [6]:
def predict_proba(theta, X):
    z = np.dot(theta, X)
    result = sigmoid(z)
    return result
    
predict_proba(theta, X)

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

In [7]:
def predict(theta, X, threshold=0.5):
    proba = predict_proba(theta, X)
    result = (proba >= threshold).astype(int)
    return result
    
predict(theta, X)

array([1, 0, 0, 1])

In [8]:
def accuracy(y_true, y_pred):
    correct_predictions = np.sum(y_true == y_pred)
    result = correct_predictions / len(y_true)
    return result

In [9]:
print(f"Імовірності належності кожного з екземплярів в матриці X до класу 1:\n{predict_proba(theta, X)}")
print(f"Передбачені класи кожного екземпляра з матриці X:\n{predict(theta, X)}")
print(f"Реальні дані по класах в залежній змінні y:\n{y}")
print(f"Точність моделі: {accuracy(y, predict(theta, X))}")

Імовірності належності кожного з екземплярів в матриці X до класу 1:
[0.77966809 0.25617965 0.42815828 0.61944235]
Передбачені класи кожного екземпляра з матриці X:
[1 0 0 1]
Реальні дані по класах в залежній змінні y:
[1 0 1 0]
Точність моделі: 0.5
